version: '3.4'

services:
 jornalerosdb:
  image: mcr.microsoft.com/mssql/server
  ports:
  - "1433" 

 rabbitmq:
  image: rabbitmq:3-management
  ports:
  - "15672"
  - "5672"

 empresasapp:
  image: ${DOCKER_REGISTRY-}empresasapp
  build:
   context: .
   dockerfile: EmpresasApp/Dockerfile

 ofertasapp:
  image: ${DOCKER_REGISTRY-}ofertasapp
  build:
    context: .
    dockerfile: OfertasApp/Dockerfile

 jornalerosapp:
  image: ${DOCKER_REGISTRY-}jornalerosapp
  build:
    context: .
    dockerfile: JornalerosApp/Dockerfile


 ocelotapigateway:
  image: ${DOCKER_REGISTRY-}ocelotapigateway
  build:
    context: .
    dockerfile: ApiGateway/Dockerfile

