version: '3.4'

services:
 blazor:
  image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

 jornalerosapp:
  image: ${DOCKER_REGISTRY-}jornalerosapp
  build:
   context: .
   dockerfile: JornalerosApp/Dockerfile