version: '3.4'

services:
 jornalerosdb:
  image: mcr.microsoft.com/mssql/server
  ports:
  - "1433" 

 rabbitmq:
  image: rabbitmq:3-management

 jornalerosapp:
  image: ${DOCKER_REGISTRY-}jornalerosapp
  build:
   context: .
   dockerfile: JornalerosApp/Dockerfile

 empresasapp:
  image: ${DOCKER_REGISTRY-}empresasapp
  build:
   context: .
   dockerfile: EmpresasApp/Dockerfile


 ofertasapp:
  image: ${DOCKER_REGISTRY-}ofertasapp
  build:
    context: .
    dockerfile: OfertasApp/Dockerfile

