version: '3.4'

services:
    jornalerosdb:
     container_name: jornalerosdb
     restart: always     
     ports:
     - "1433:1433"
     environment:
      SA_PASSWORD: "odynJRiC12"
      ACCEPT_EULA: "Y"

    jornalerosapp:
     container_name: jornalerosapp
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:ContainerConnection=jornalerosdb:1433"
     ports:
      - "8000:80"      
     volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
     depends_on:
     - jornalerosdb

    empresasapp:
     container_name: empresasapp
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:ContainerConnection=jornalerosdb:1433"
     ports:
      - "8001:80"     
     volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
     depends_on:
     - jornalerosdb
