version: '3.4'

services:

  sqldata:
      image: mcr.microsoft.com/mssql/server:2017-latest

  jornalerosapp:
    image: ${DOCKER_REGISTRY-}jornalerosapp
    build:
      context: .
      dockerfile: JornalerosApp/Dockerfile

      depends_on:
      - sqldata      
     

 
