version: '3.4'

services:
    sqldata:
        container_name: sqldata
        ports:
            - "11433:1433"
        environment:
            SA_PASSWORD: "odynJRiC12"
            ACCEPT_EULA: "Y"

    jornalerosapp:
         environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
         ports:
          - "80:80"
          - "44339:443"
         volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

         depends_on:
                - sqldata
